{% set version = "2.9.1" %}
{% set name = "catch2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tgz
  url: https://github.com/catchorg/Catch2/archive/v{{ version }}.tar.gz
  sha256: 0b36488aca6265e7be14da2c2d0c748b4ddb9c70a1ea4da75736699c629f14ac

build:
  skip: true  # [win and vc<14]
  number: 0

  ignore_run_exports:
    - {{ compiler('cxx') }}
    - libstdcxx-ng  # [linux]
    - libcxx  # [osx]
    - vc  # [win]


requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja

about:
  home: https://github.com/catchorg/Catch2/
  license: BSL-1.0
  license_file: LICENSE.txt
  summary: |
    A modern, C++-native, header-only, test framework for unit-tests, TDD and BDD - using
    C++11, C++14, C++17 and later (or C++03 on the Catch1.x branch).
  description: |
    Catch2 stands for C++ Automated Test Cases in a Header and is a multi-paradigm test framework
    for C++. which also supports Objective-C (and maybe C). It is primarily distributed as a single
    header file, although certain extensions may require additional headers.
  doc_url: https://github.com/catchorg/Catch2/blob/master/docs/Readme.md
  dev_url: https://github.com/catchorg/Catch2

extra:
  recipe-maintainers:
    - mjscosta
