{% set version = "3.8.1" %}
{% set name = "catch2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tgz
  url: https://github.com/catchorg/Catch2/archive/v{{ version }}.tar.gz
  sha256: 18b3f70ac80fccc340d8c6ff0f339b2ae64944782f8d2fca2bd705cf47cadb79

build:
  number: 0
  run_exports: {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja

about:
  home: https://github.com/catchorg/Catch2
  license: BSL-1.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: |
    A modern, C++-native, test framework for unit-tests, TDD and BDD 
    - using C++14, C++17 and later (C++11 support is in v2.x branch, and C++03 on the Catch1.x branch)
  description: |
    Catch2 is mainly a unit testing framework for C++, 
    but it also provides basic micro-benchmarking features, and simple BDD macros.

    Catch2's main advantage is that using it is both simple and natural. 
    Test names do not have to be valid identifiers, 
    assertions look like normal C++ boolean expressions, 
    and sections provide a nice and local way to share set-up and tear-down code in tests.
  doc_url: https://github.com/catchorg/Catch2/blob/v{{ version }}/docs/Readme.md
  dev_url: https://github.com/catchorg/Catch2

extra:
  recipe-maintainers:
    - eunos-1128
    - mjscosta
    - tdegeus
